name: Sync on DOM Cloud
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: >-
            {"commands":["git pull origin main","NPM=`which npm`","$NPM
            ci --omit=dev","npm run db:migrate:prod","npm run
            db:generate","restart"],"features":["node
            lts"],"nginx":{"root":"public_html/public","passenger":{"enabled":"on","app_env":"production","app_start_command":"env
            PORT=$PORT node app.js"}}}
