name: Sync on DOM Cloud
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: >-
            {"nginx":{"index":"index.html","root":"public_html/public","passenger":{"enabled":"on","app_start_command":"env
            PORT=$PORT node app.js","app_env":"production"}},"commands":["npm
            install"],"webhook_id":"Dari-Hati-Mencari-Solusi/volunteerin-api#662fe6ca16a6ea69962c29440bec79c02939c3a2"}
